In [3]:
import numpy as np

x = [1, 2, 3, 4, 5]
y = [3, 4, 2, 4, 5]

x_mean = np.mean(x)
y_mean = np.mean(y)

print("Mean of x:", x_mean)
print("Mean of y:", y_mean)

Mean of x: 3.0
Mean of y: 3.6


In [9]:
#line equation= y=mx+c
#3.6=m*3.0+c

y2 = y-y_mean
y2

array([-0.6,  0.4, -1.6,  0.4,  1.4])

In [19]:
x2=x-x_mean
x2

array([-2., -1.,  0.,  1.,  2.])

In [12]:
y_square= (y2)**2
y_square

array([0.36, 0.16, 2.56, 0.16, 1.96])

In [13]:
yp=[2.8,3.2,3.6,4.0,4.4]
yp

[2.8, 3.2, 3.6, 4.0, 4.4]

In [17]:
e=yp-y_mean
e

array([-0.8, -0.4,  0. ,  0.4,  0.8])

In [18]:
e_square=e**2
e_square

array([0.64, 0.16, 0.  , 0.16, 0.64])

In [23]:
mul=x2*y2
mul

array([ 1.2, -0.4, -0. ,  0.4,  2.8])

In [25]:
mul_sum=np.sum(mul)
mul_sum

4.0

In [26]:
x2_sqr=x2**2
x2_sqr

array([4., 1., 0., 1., 4.])

In [27]:
x2_d=np.sum(x2_sqr)
x2_d

10.0

In [31]:
m=mul_sum /x2_d
print("mean:",m)

mean: 0.4


In [30]:
#line eqn= y=mx+c
#c=y-mx
#3.6= 0.4 * 3.0 +c
c=y_mean-(m*x_mean)
c

2.4

In [42]:
#final line equation :
#y=0.4x+2.4
x_new = [1,2,3,4,5]
x_1 = [x * 0.4 for x in x_new]
y_p = [x + 2.4 for x in x_1]
print("y_p:", y_p)


y_p: [2.8, 3.2, 3.6, 4.0, 4.4]


In [34]:
import numpy as np

def compute_line_equation(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    y2 = y - y_mean
    x2 = x - x_mean
    y_square = y2 ** 2
    x_square = x2 ** 2
    mul = x2 * y2
    mul_sum = np.sum(mul)
    x2_sqr = np.sum(x_square)
    m = mul_sum / x2_sqr
    c = y_mean - (m * x_mean)
    return m, c, f"y = {m}x + {c}"

x = [1, 2, 3, 4, 5]
y = [3, 4, 2, 4, 5]

m, c, line_eqn = compute_line_equation(x, y)

print("Slope (m):", m)
print("Intercept (c):", c)
print("Equation of the line:", line_eqn)


Slope (m): 0.4
Intercept (c): 2.4
Equation of the line: y = 0.4x + 2.4


In [46]:
import numpy as np

def compute_line_equation(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    y2 = y - y_mean
    x2 = x - x_mean
    mul = x2 * y2
    mul_sum = np.sum(mul)
    x2_sqr = np.sum(x2 ** 2)
    m = mul_sum / x2_sqr
    c = y_mean - (m * x_mean)
    return m, c

def predict(x_values, m, c):
    return m * np.array(x_values) + c

x = [1, 2, 3, 4, 5]
y = [3, 4, 2, 4, 5]

m, c = compute_line_equation(x, y)

print(f"Equation of the line: y = {m}x + {c}")

x_new = [1,2,3,4,5]
y_p = predict(x_new, m, c)

print(f"Predictions for x = {x_new}: y = {y_p}")



Equation of the line: y = 0.4x + 2.4
Predictions for x = [1, 2, 3, 4, 5]: y = [2.8 3.2 3.6 4.  4.4]


In [49]:
#r-squared

def r2(y_p, y_a):
    y_mean = np.mean(y_a)
    ss_total = np.sum((y_a - y_mean) ** 2)
    ss_residual = np.sum((y_a - y_p) ** 2)
    return 1 - (ss_residual / ss_total)


r_squared = r2(y_p, y)
print(f"R-squared: {r_squared}")

R-squared: 0.3076923076923078


In [48]:
import numpy as np

def compute_line_equation(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    y2 = y - y_mean
    x2 = x - x_mean
    mul = x2 * y2
    mul_sum = np.sum(mul)
    x2_sqr = np.sum(x2 ** 2)
    m = mul_sum / x2_sqr
    c = y_mean - (m * x_mean)
    return m, c

def predict(x_values, m, c):
    return m * np.array(x_values) + c

def r2(y_p, y_true):
    y_mean = np.mean(y_true)
    ss_total = np.sum((y_true - y_mean) ** 2)
    ss_residual = np.sum((y_true - y_p) ** 2)
    return 1 - (ss_residual / ss_total)

x = [1, 2, 3, 4, 5]
y = [3, 4, 2, 4, 5]

m, c = compute_line_equation(x, y)

print(f"Equation of the line: y = {m}x + {c}")

x_new = [1, 2, 3, 4, 5]
y_p = predict(x_new, m, c)

print(f"Predictions for x = {x_new}: y = {y_p}")

r_squared = r2(y_p, y)
print(f"R-squared: {r_squared}")


Equation of the line: y = 0.4x + 2.4
Predictions for x = [1, 2, 3, 4, 5]: y = [2.8 3.2 3.6 4.  4.4]
R-squared: 0.3076923076923078
