In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
df=sns.load_dataset("diamonds")

In [3]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [5]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [6]:
cols=['cut', 'color', 'clarity','price']
for col in cols:
  print(df[col].unique())

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']
['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']
[ 326  327  334 ... 2753 2755 2756]


In [7]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(146)

In [9]:
df.shape

(53940, 10)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.shape

(53794, 10)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53794 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53794 non-null  float64 
 1   cut      53794 non-null  category
 2   color    53794 non-null  category
 3   clarity  53794 non-null  category
 4   depth    53794 non-null  float64 
 5   table    53794 non-null  float64 
 6   price    53794 non-null  int64   
 7   x        53794 non-null  float64 
 8   y        53794 non-null  float64 
 9   z        53794 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.4 MB


In [13]:
df.describe()

carat         depth         table         price             x  \
count  53794.00000  53794.000000  53794.000000  53794.000000  53794.000000   
mean       0.79778     61.748080     57.458109   3933.065082      5.731214   
std        0.47339      1.429909      2.233679   3988.114460      1.120695   
min        0.20000     43.000000     43.000000    326.000000      0.000000   
25%        0.40000     61.000000     56.000000    951.000000      4.710000   
50%        0.70000     61.800000     57.000000   2401.000000      5.700000   
75%        1.04000     62.500000     59.000000   5326.750000      6.540000   
max        5.01000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53794.000000  53794.000000  
mean       5.734653      3.538714  
std        1.141209      0.705037  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.030000  
max       58.900000     31.800000

In [14]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [15]:
numeric_cols =['carat','depth','table','price','x','y','z']

outlier_counts = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_counts[col] = len(outliers)

for col, count in outlier_counts.items():
    print(f"{col}: {count} outliers")

carat: 1873 outliers
depth: 2525 outliers
table: 604 outliers
price: 3523 outliers
x: 31 outliers
y: 28 outliers
z: 48 outliers


In [16]:

def remove_outliers_zscore(df, column, threshold=3):
    mean = df[column].mean()
    std = df[column].std()
    z_scores = (df[column] - mean) / std
    df_cleaned = df[(z_scores < threshold) & (z_scores > -threshold)].copy()
    return df_cleaned

for col in numeric_cols:
    df = remove_outliers_zscore(df, col)

df.shape

(51051, 10)

In [17]:
numeric_cols =['carat','depth','table','price','x','y','z']

outlier_counts = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_counts[col] = len(outliers)

for col, count in outlier_counts.items():
    print(f"{col}: {count} outliers")

carat: 867 outliers
depth: 2051 outliers
table: 7 outliers
price: 2515 outliers
x: 0 outliers
y: 0 outliers
z: 0 outliers


In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cat_cols=['cut','color','clarity']
for col in cat_cols:
  df[col]=le.fit_transform(df[col])


In [19]:
df.dtypes

carat      float64
cut          int64
color        int64
clarity      int64
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [20]:
df.head()

carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23    2      1        3   61.5   55.0    326  3.95  3.98  2.43
1   0.21    3      1        2   59.8   61.0    326  3.89  3.84  2.31
3   0.29    3      5        5   62.4   58.0    334  4.20  4.23  2.63
4   0.31    1      6        3   63.3   58.0    335  4.34  4.35  2.75
5   0.24    4      6        7   62.8   57.0    336  3.94  3.96  2.48

In [21]:
cols=['cut', 'color', 'clarity','price']
for col in cols:
  print(df[col].unique())

[2 3 1 4 0]
[1 5 6 4 2 3 0]
[3 2 5 7 6 4 0 1]
[ 326  334  335 ... 2753 2755 2756]


In [22]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [23]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
cols=['carat', 'price', 'color', 'clarity', 'depth', 'table', 'x', 'y','z']
df[cols]=scaler.fit_transform(df[cols])


In [24]:
df.head()

carat  cut     color   clarity     depth     table     price         x  \
0 -1.250630    2 -0.923606 -0.501530 -0.203850 -1.136698 -0.955505 -1.616646   
1 -1.298233    3 -0.923606 -1.080889 -1.550180  1.777345 -0.955505 -1.673758   
3 -1.107821    3  1.438432  0.657188  0.508913  0.320323 -0.953128 -1.378676   
4 -1.060218    1  2.028942 -0.501530  1.221676  0.320323 -0.952831 -1.245413   
5 -1.226828    4  2.028942  1.815907  0.825697 -0.165350 -0.952534 -1.626164   

          y         z  
0 -1.602155 -1.631903  
1 -1.736304 -1.816793  
3 -1.362602 -1.323753  
4 -1.247617 -1.138863  
5 -1.621319 -1.554865

In [25]:
df.dtypes

carat      float64
cut          int64
color      float64
clarity    float64
depth      float64
table      float64
price      float64
x          float64
y          float64
z          float64
dtype: object

In [26]:
x=df.drop('cut',axis=1)
y=df['cut']

In [27]:
x.shape

(51051, 9)

In [28]:
y.shape

(51051,)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train.shape

(40840, 9)

In [31]:
x_test.shape

(10211, 9)

In [32]:
y_train.shape

(40840,)

In [33]:
y_test.shape

(10211,)

In [34]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)

**RandomForestClassifier**

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf=RandomForestClassifier()
rf.fit(x_train,y_train)


RandomForestClassifier()

In [36]:
y_pred=rf.predict(x_test)
y_pred


array([4, 2, 4, ..., 2, 2, 4])

In [37]:
y_pred.shape

(10211,)

In [38]:
print(np.unique(y_pred))

[0 1 2 3 4]


In [39]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.7881696209969641


In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85       175
           1       0.79      0.68      0.73       857
           2       0.83      0.92      0.87      4183
           3       0.77      0.82      0.80      2636
           4       0.70      0.55      0.62      2360

    accuracy                           0.79     10211
   macro avg       0.79      0.76      0.77     10211
weighted avg       0.78      0.79      0.78     10211



**DecisionTreeClassifier**

In [41]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [42]:
y_pred_tree=dt.predict(x_test)
y_pred_tree

array([4, 2, 4, ..., 3, 2, 4])

In [43]:
y_pred_tree.shape

(10211,)

In [44]:
print(np.unique(y_pred_tree))

[0 1 2 3 4]


In [45]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred_tree)
print(accuracy)

0.7112917441974341


In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_tree))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       175
           1       0.66      0.64      0.65       857
           2       0.80      0.80      0.80      4183
           3       0.73      0.73      0.73      2636
           4       0.54      0.55      0.55      2360

    accuracy                           0.71     10211
   macro avg       0.71      0.71      0.71     10211
weighted avg       0.71      0.71      0.71     10211



**GradientBoostingClassifier**

In [47]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [48]:
y_pred_gb=gb.predict(x_test)
y_pred_gb

array([4, 2, 3, ..., 2, 2, 4])

In [49]:
y_pred_gb.shape

(10211,)

In [50]:
print(np.unique(y_pred_gb))

[0 1 2 3 4]


In [51]:
from sklearn.metrics import accuracy_score,classification_report
accuracy=accuracy_score(y_test,y_pred_gb)
print(accuracy)
print(classification_report(y_test,y_pred_gb))

0.7610420135148369
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       175
           1       0.82      0.62      0.70       857
           2       0.82      0.92      0.87      4183
           3       0.69      0.85      0.76      2636
           4       0.68      0.43      0.53      2360

    accuracy                           0.76     10211
   macro avg       0.77      0.73      0.74     10211
weighted avg       0.76      0.76      0.75     10211

