**TASKS**

In [1]:
import numpy as np

**1)array creation**

In [9]:
#create 1d array of numbers from 10 to 50
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
#create a 3x3 array of random numbers between 0 and 1
rarr=np.random.rand(3, 3)
rarr

array([[0.68042126, 0.06650003, 0.2453434 ],
       [0.7995128 , 0.51714487, 0.73524987],
       [0.82244158, 0.34294903, 0.48517089]])

**2)Array Attributes**

In [4]:
#find the shape size and datatype of the array you created in previous task
print("shape:",np.shape(rarr))
print("size:",np.size(rarr))
print("datatype:",rarr.dtype)

shape: (3, 3)
size: 9
datatype: float64


**3)Basic Operations**

In [5]:
#add 5 to every element of 1d array
a=[1,2,3,4,5]
b=np.add(a,5)
b

array([ 6,  7,  8,  9, 10])

In [6]:
#Multipy 2 2d arrays element wise 
arr1 = np.random.rand(3, 3)
arr1


array([[0.96586783, 0.07041984, 0.69979351],
       [0.38772511, 0.63686574, 0.78225344],
       [0.66783306, 0.16218957, 0.05779855]])

In [7]:
arr2 = np.random.rand(3, 3)
arr2

array([[0.91485998, 0.14973845, 0.78559009],
       [0.31954313, 0.24326995, 0.02004085],
       [0.52271023, 0.2856228 , 0.72088404]])

In [8]:
mul=np.dot(arr1,arr2)
mul

array([[1.27192523, 0.36163556, 1.26465744],
       [0.96711214, 0.43641707, 0.88127036],
       [0.6930122 , 0.15596472, 0.5695595 ]])

**4)Indexing and slicing**

In [11]:
#create a 5x5 array of integers from 1 to 25 .extract: 
#.The first row 
#.the last column 
#.a subarray of the first 3 rows and first 2 columns
fivearr = np.arange(1, 26).reshape(5, 5)
fivearr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
#.The first row 
fivearr[0, :]

array([1, 2, 3, 4, 5])

In [13]:
#.the last column
fivearr[:,-1]

array([ 5, 10, 15, 20, 25])

In [14]:
#.a subarray of the first 3 rows and first 2 columns
fivearr[:3, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

**5)Aggregation**

In [15]:
#create 10-element array of random integers between 1 to 100.find:
#the max value
#the min value
#the mean and std
random_ints = np.random.randint(1, 101, size=10)
random_ints


array([75, 54,  1, 36, 53,  3, 73, 81, 59, 40], dtype=int32)

In [16]:
#the max value
np.max(random_ints)

np.int32(81)

In [17]:
#the min value
np.min(random_ints)

np.int32(1)

In [19]:
#the mean 
np.mean(random_ints)


np.float64(47.5)

In [20]:
#and std
np.std(random_ints)

np.float64(26.57912714894904)

**6)Reshaping**

In [28]:
#convert a 1d array of numbers from 1 to 12 into 3x4 matrix
arr_3=np.arange(1,13)
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
reshaped_arr = arr_3.reshape(3, 4)
reshaped_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**7)Broadcasting**

In [35]:
#create a 3x3 martrix of ones.add a 1d array[1,2,3] to eac row 
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
e=[1,2,3]
f=np.add(ones,e)
f

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**8)Filtering**

In [37]:
#create a 1D array of random integers between 1 and 50 .
#extract all elements that are divisible by 5
rand_a=np.arange(1,50)
rand_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
for i in rand_a :
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45


**9)Matrix multiplication**

In [46]:
#create 2 2x2 martices and perform matrix multiplication
var1 = np.random.rand(2, 2)
var1

array([[0.66204968, 0.41875228],
       [0.99924281, 0.41029466]])

In [47]:
var2=np.random.rand(2,2)
var2

array([[0.39200377, 0.38620372],
       [0.03182708, 0.72130877]])

In [48]:
var3=np.dot(var1,var2)
var3

array([[0.27285363, 0.55773573],
       [0.40476543, 0.68186042]])

**10)Advanced Indexing**

In [49]:
#given a 4x4 matrix ,use fancy indexing to extract the diagonal elements
mat= np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
dia_eles = mat[np.arange(4), np.arange(4)]
dia_eles

array([ 1,  6, 11, 16])

In [51]:
np.diagonal(mat)

array([ 1,  6, 11, 16])